/**
 * Created by MoonJR on 2016. 4. 4..
 */
const FLAG_UNKNOWN_ERROR_CODE = 9999;
const FLAG_DB_CONNECTION_ERROR_CODE = 1000;
const FLAG_ALREADY_REG_VIDEO_CODE = 2000;
const FLAG_NOT_EXIST_VIDEO_CODE = 2001;

const FLAG_ALREADY_REG_CATEGORY_CODE = 3000;
const FLAG_NOT_EXIST_CATEGORY_CODE = 3001;
const FLAG_NOT_AVAILABLE_CATEGORY_CODE = 3003;
const FLAG_ALREADY_EXIST_OTHER_TABLE_CODE = 3004;

const FLAG_LACK_VARIABLE_CODE = 4000;

const FLAG_SUCCESS_CODE = 0;

const FLAG_UNKNOWN_ERROR_MSG = '예상치 않은 오류 발생';
const FLAG_DB_CONNECTION_ERROR_MSG = '데이터 베이스 서버에 연결 할 수 없습니다.';
const FLAG_ALREADY_REG_VIDEO_MSG = '이미 존재하는 영상 입니다.';
const FLAG_ALREADY_REG_CATEGORY_MSG = '이미 존재하는 카테고리 입니다.';
const FLAG_NOT_EXIST_VIDEO_MSG = '존재하지 않는 영상 입니다.';
const FLAG_NOT_EXIST_CATEGORY_MSG = '존재하지 않는 카테고리 입니다.';
const FLAG_NOT_AVAILABLE_CATEGORY_MSG = '사용 불가능한 카테고리 아이디 입니다.';
const FLAG_ALREADY_EXIST_OTHER_TABLE_MSG = '다른 테이블에서 사용중인 아이디 입니다.';
const FLAG_LACK_VARIABLE_MSG = '매개변수가 부족합니다.';


const FLAG_SUCCESS_MSG = '성공';

exports.FLAG_UNKNOWN_ERROR_JSON = {
    code: FLAG_UNKNOWN_ERROR_CODE,
    msg: FLAG_UNKNOWN_ERROR_MSG
};
exports.FLAG_DB_CONNECTION_ERROR_JSON = {
    code: FLAG_DB_CONNECTION_ERROR_CODE,
    msg: FLAG_DB_CONNECTION_ERROR_MSG
};
exports.FLAG_ALREADY_REG_VIDEO_JSON = {
    code: FLAG_ALREADY_REG_VIDEO_CODE,
    msg: FLAG_ALREADY_REG_VIDEO_MSG
};
exports.FLAG_NOT_EXIST_VIDEO_JSON = {
    code: FLAG_NOT_EXIST_VIDEO_CODE,
    msg: FLAG_NOT_EXIST_VIDEO_MSG
};

exports.FLAG_ALREADY_REG_CATEGORY_JSON = {
    code: FLAG_ALREADY_REG_CATEGORY_CODE,
    msg: FLAG_ALREADY_REG_CATEGORY_MSG
};
exports.FLAG_NOT_EXIST_CATEGORY_JSON = {
    code: FLAG_NOT_EXIST_CATEGORY_CODE,
    msg: FLAG_NOT_EXIST_CATEGORY_MSG
};
exports.FLAG_NOT_AVAILABLE_CATEGORY_JSON = {
    code: FLAG_NOT_AVAILABLE_CATEGORY_CODE,
    msg: FLAG_NOT_AVAILABLE_CATEGORY_MSG

};

exports.FLAG_ALREADY_EXIST_OTHER_TABLE_JSON = {
    code: FLAG_ALREADY_EXIST_OTHER_TABLE_CODE,
    msg: FLAG_ALREADY_EXIST_OTHER_TABLE_MSG

};

exports.FLAG_LACK_VARIABLE_JSON = {
    code: FLAG_LACK_VARIABLE_CODE,
    msg: FLAG_LACK_VARIABLE_MSG
};

exports.FLAG_SUCCESS_JSON = {
    code: FLAG_SUCCESS_CODE,
    msg: FLAG_SUCCESS_MSG
};